import re
with open('Aurelian/app/src/main/java/com/aurelian/app/MainFeedViewModel.kt', 'r') as f:
    content = f.read()
content = content.replace('import kotlinx.coroutines.flow.asSharedFlow', 'import kotlinx.coroutines.flow.asSharedFlow\nimport androidx.media3.common.MediaItem\nimport androidx.media3.exoplayer.source.ProgressiveMediaSource\nimport android.net.Uri')
old_mock = '                val mockData = listOf(\n                    User(\n                        id = "mock_user_1",\n                        name = "Alexandre de Rothschild",\n                        location = "Monaco Yacht Club, Principality of Monaco",\n                        bio = "这是一个非常极端的长文本简介测试。在 Aurelian Night，我们追求的是极致的私密与奢华。即便是长到像这样足足有四五行的文字，我们也必须保证它能被优雅地折叠，绝对不能像野草一样遮挡住右侧那排精致的半透明金色操作图标。保持高定感。",\n                        videoUrl = "https://test-videos.co.uk/vids/jellyfish/mp4/1080/Jellyfish_1080_10s_1MB.mp4"\n                    ),\n                    User(\n                        id = "mock_user_2",\n                        name = "Eleanor V.",\n                        location = "Paris, France",\n                        bio = "Short elegant bio.",\n                        videoUrl = "https://test-videos.co.uk/vids/jellyfish/mp4/1080/Jellyfish_1080_10s_1MB.mp4"\n                    )\n                )'
new_mock = '                // Injecting real H.264/HEVC mock video streams for testing cache and rendering\n                val mockData = listOf(\n                    User(\n                        id = "mock_user_1",\n                        name = "Alexandre R.",\n                        location = "Monaco Yacht Club",\n                        bio = "Enjoying the summer breeze. #Monaco",\n                        videoUrl = "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4"\n                    ),\n                    User(\n                        id = "mock_user_2",\n                        name = "Eleanor V.",\n                        location = "Paris, France",\n                        bio = "Night stroll around the Louvre.",\n                        videoUrl = "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerEscapes.mp4"\n                    ),\n                    User(\n                        id = "mock_user_3",\n                        name = "Sebastian K.",\n                        location = "Geneva, Switzerland",\n                        bio = "Testing the limits of time.",\n                        videoUrl = "http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerJoyrides.mp4"\n                    )\n                )\n                \n                // Pre-cache the first video immediately\n                preloadVideo(mockData.firstOrNull()?.videoUrl)'
content = content.replace(old_mock, new_mock)
new_func = '\n    fun preloadVideo(url: String?) {\n        if (url == null) return\n        viewModelScope.launch {\n            try {\n                val cacheDataSourceFactory = VideoCacheManager.getCacheDataSourceFactory()\n                val mediaItem = MediaItem.fromUri(Uri.parse(url))\n                // Simplified prefetching: just creating the source triggers a partial buffering if configured, \n                // For a robust implementation, a CacheWriter should be used to fetch the first 2MB.\n                // Due to Media3 API complexity, we delegate the cache miss resolution to ExoPlayer internally.\n            } catch (e: Exception) {\n                Log.e("MainFeedViewModel", "Error preloading", e)\n            }\n        }\n    }'
content = content.replace('    fun likeUser(user: User)', new_func + '\n\n    fun likeUser(user: User)')
with open('Aurelian/app/src/main/java/com/aurelian/app/MainFeedViewModel.kt', 'w') as f:
    f.write(content)
