import re
with open('Aurelian/app/src/main/java/com/aurelian/app/MainFeedScreen.kt', 'r') as f:
    content = f.read()
content = content.replace('import androidx.media3.ui.PlayerView', 'import androidx.media3.ui.PlayerView\nimport androidx.media3.exoplayer.source.ProgressiveMediaSource\nimport androidx.compose.animation.AnimatedVisibility\nimport androidx.compose.animation.core.tween\nimport androidx.compose.animation.fadeIn\nimport androidx.compose.animation.fadeOut')
old_p = '    val exoPlayer = remember {\n        ExoPlayer.Builder(context).build().apply {\n            val mediaItem = MediaItem.fromUri(Uri.parse(user.videoUrl))\n            setMediaItem(mediaItem)\n            repeatMode = Player.REPEAT_MODE_ALL\n            prepare()\n        }\n    }'
new_p = '    var isVideoReady by remember { mutableStateOf(false) }\n\n    val exoPlayer = remember {\n        val cacheDataSourceFactory = VideoCacheManager.getCacheDataSourceFactory()\n        val mediaItem = MediaItem.fromUri(Uri.parse(user.videoUrl))\n        val mediaSource = ProgressiveMediaSource.Factory(cacheDataSourceFactory)\n            .createMediaSource(mediaItem)\n\n        ExoPlayer.Builder(context).build().apply {\n            setMediaSource(mediaSource)\n            repeatMode = Player.REPEAT_MODE_ALL\n            addListener(object : Player.Listener {\n                override fun onPlaybackStateChanged(playbackState: Int) {\n                    if (playbackState == Player.STATE_READY) {\n                        isVideoReady = true\n                    }\n                }\n            })\n            prepare()\n        }\n    }'
content = content.replace(old_p, new_p)
old_v = '        // Video Player Background\n        AndroidView(\n            factory = { ctx ->\n                PlayerView(ctx).apply {\n                    player = exoPlayer\n                    useController = false\n                    resizeMode = AspectRatioFrameLayout.RESIZE_MODE_ZOOM\n                    layoutParams = FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT)\n                }\n            },\n            modifier = Modifier.fillMaxSize()\n        )'
new_v = '        // Background Placeholder (Cover Image)\n        AsyncImage(\n            model = user.videoUrl, \n            contentDescription = "Cover Image",\n            contentScale = ContentScale.Crop,\n            modifier = Modifier.fillMaxSize()\n        )\n\n        // Video Player Background with Fade-in Animation\n        AnimatedVisibility(\n            visible = isVideoReady,\n            enter = fadeIn(animationSpec = tween(700)),\n            exit = fadeOut()\n        ) {\n            AndroidView(\n                factory = { ctx ->\n                    PlayerView(ctx).apply {\n                        player = exoPlayer\n                        useController = false\n                        resizeMode = AspectRatioFrameLayout.RESIZE_MODE_ZOOM\n                        layoutParams = FrameLayout.LayoutParams(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT)\n                    }\n                },\n                modifier = Modifier.fillMaxSize()\n            )\n        }'
content = content.replace(old_v, new_v)
with open('Aurelian/app/src/main/java/com/aurelian/app/MainFeedScreen.kt', 'w') as f:
    f.write(content)
